#!/usr/bin/env python
import sys

import ec2price.app


if __name__ == '__main__':
    try:
        ec2price.app.main(sys.argv[1:])
    except KeyboardInterrupt:
        print >> sys.stderr, 'interrupted'
